GET http://localhost:2030/usuarios

###

GET http://localhost:2030/usuarios/1

###

POST http://localhost:2030/usuarios
Content-Type: application/json

    
    {
        "username": "Cattuc",
        "password": "1DJfuj675434"
    }

###
PUT http://localhost:2030/usuarios/6
Content-Type: application/json

{
    "id": 6,
    "username": "sunset",
    "password": "Fobayol456(*)"
}

###

DELETE http://localhost:2030/usuarios/4 HTTP/1.1

------------------------------------------------------------
###
GET http://localhost:3000/notes

###
POST http://localhost:3000/notes
Content-Type: application/json

{
    "tittle": "that is funny l think :O",
    "content": "your are wimpy wimp... don't believe that"
}

###
DELETE http://localhost:3000/notes/6a4c7c899aa0ffd80d21c6a4

###
PUT http://localhost:3000/notes/6a4c6ec99b912a95e9605bb7
Content-Type: application/json

{
    "tittle": "that is funny l think",
    "content": "your are wimpy wimp... don't believe that what talking about l tired lest go to bed, yes? :)"
}