GET http://localhost:2030/usuarios

###

GET http://localhost:2030/usuarios/1

###

POST http://localhost:2030/usuarios
Content-Type: application/json


    {
        "username": "Cattuc",
        "password": "1DJfuj675434"
    }


###
PUT http://localhost:2030/usuarios/6
Content-Type: application/json

{
    "id": 6,
    "username": "sunset",
    "password": "Fobayol456(*)"
}

###

DELETE http://localhost:2030/usuarios/4 HTTP/1.1