GET http://localhost:2230/usuarios

###

GET http://localhost:2230/usuarios/5

###

POST http://localhost:2230/usuarios
Content-type: application/json

{
    "id": 5,
    "name": "sunny"
}

###

PUT http://localhost:2230/usuarios/6
Content-type: application/json

{
    "name": "Sunset"
}