GET http://localhost:2030/usuarios

###

GET http://localhost:2030/usuarios/5

###

POST http://localhost:2030/usuarios
Content-type: application/json
[

    {
        "id": 8,
        "name": "sunny",
        "password": "1234"
    }
]

###

    PUT http://localhost:2030/usuarios/6
Content-type: application/json

{
    "name": "Sunset"
}
###
DELETE http://localhost:2030/usuarios/4 HTTP/1.1