GET http://localhost:2030/usuarios

###

GET http://localhost:2030/usuarios/5

###

POST http://localhost:2030/usuarios
Content-Type: application/json

[
    {
        "name": "sunny",
        "password": "1234"
    }
]

###

PUT http://localhost:2030/usuarios/6
Content-Type: application/json

{
    "id": 6,
    "name": "Sunset",
    "password": "5678"
}
###

DELETE http://localhost:2030/usuarios/4 HTTP/1.1