GET http://localhost:2030/usuarios

###

GET http://localhost:2030/usuarios/5

###

POST http://localhost:2030/usuarios
Content-type: application/json
[

    {
        "id": 5,
        "name": "sunny"
    }
]

###

PUT http://localhost:2030/usuarios/6
Content-type: application/json

{
    "name": "Sunset"
}